ALTER TABLE tasks DROP COLUMN IF EXISTS repeat_every_days;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence JSONB NOT NULL DEFAULT '{"type":"none"}';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ NOT NULL DEFAULT NOW();
